### ISSUE TITLE
Transfer existing repo with issues to this one

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/assessment#1]
@gvwilson I have a repository on the student assessment here: https://github.com/chendaniely/assessment-student-post-workshop

should I rename it to `assessment` and transfer ownership to swcarpentry?  would we loose the issues if I do that?

**Comment by gvwilson** [comment]
We've had poor luck renaming repos and transferring content - given how 
slim the content, I'd suggest copying the content of the issues over to 
the new swcarpentry/assessment repo and shutting down 
assessment-student-post-workshop.
Thanks,
Greg

**Comment by chendaniely** [comment]
@gvwilson should I put meeting notes here? or should they be sent as PR's to the `board` repo?

**Comment by gvwilson** [comment]
I think they should be PRs to the board repo.

**Comment by chendaniely** [comment]
@gvwilson closing this PR as I think everything has been transferred over and we are using this repository as the main entry point for the assessments.

**Comment by gvwilson** [comment]
Thanks Daniel.
