### ISSUE TITLE
Demographics question

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/assessment#13]
Not sure if this repo is active...

Can we change the question about race/ethnicity

>  Which race/ethnicity best describes you? (Please choose only one.)

to be a multi choice instead of choose one?

**Comment by katieannemills** [comment]
and a free-text write in option, too?

**Comment by maneesha** [comment]
I have access to do it... I just want people to agree with me before I make the change.

**Comment by maneesha** [comment]
Closing as outdated.
